[package]
name = "windows-installer"
edition.workspace = true
rust-version.workspace = true
description = "Pack the VPN.vu installer for several platforms into a one executable"
repository.workspace = true
license.workspace = true

[package.metadata.winres]
ProductName = "VPN.vu"
CompanyName = "VPN.vu"
LegalCopyright = "(c) 2026 VPN.vu"
InternalName = "vpnvu-installer"
OriginalFilename = "VPNvu.exe"

[build-dependencies]
anyhow.workspace = true
mullvad-version = { path = "../mullvad-version" }
windows-sys = { version = "0.52.0", features = [
  "Win32_System",
  "Win32_System_LibraryLoader",
  "Win32_System_SystemServices"
] }
winres = "0.1"

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
anyhow.workspace = true
talpid-platform-metadata = { path = "../talpid-platform-metadata" }
tempfile = "3.10"
windows-sys = { version = "0.52.0", features = [
  "Win32_System",
  "Win32_System_LibraryLoader",
  "Win32_System_SystemInformation",
  "Win32_System_Threading"
] }

[lints]
workspace = true
